[package]
name = "validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
serde = { version = "1.0.101", features = ["derive"] }
state = { workspace = true }
mempool = { workspace = true }
left-right = "0.11.5"
lr_trie = { workspace = true }
patriecia = { workspace = true }
sha256 = "1.0.2"
bytebuffer = "0.2.1"
blake3 = "0.3.8"
bincode = { workspace = true }
lrdb = { workspace = true }
vrrb_core = { workspace = true }
primitives = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
telemetry = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
